// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfwijinesqjufvrawhfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmd2lqaW5lc3FqdWZ2cmF3aGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODIxNDEsImV4cCI6MjA2MTE1ODE0MX0.6dKCbAHV7OklhKC0zevKKDm_GK9qk-k-13u0NujaeMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);