// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjpgmlzbkteaoedmjgmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqcGdtbHpia3RlYW9lZG1qZ21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjE1OTQsImV4cCI6MjA2NjMzNzU5NH0.aAJUuLK3C8D03jcZILqtRbk31jRq0fsVsoI0ycA-KM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);